server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: service-discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true
