server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: stock-adapter

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true