server:
  port: ${SERVER_PORT:8087}

spring:
  application:
    name: user-service

redis:
  server:
    urls: redis://redis:6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true